version: '3.7'

services:
  learning:
    build:
      dockerfile: ./Dockerfile
      context: ./
    restart: always
    links:
      - redis
      - tcpserver
    depends_on:
      - redis
      - tcpserver
    ports:
      - "8081:8081"

  tcpserver:
    build:
      dockerfile: ./Dockerfile
      context: ./build/package/TCP_server/
    restart: always
    expose:
      - "9999"
    ports:
      - "9999:9999"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"